### ISSUE TITLE
Add papers

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/awesome-arm-in-smart-agriculture#2]
1. https://ieeexplore.ieee.org/document/9873094

**Comment by firefly-cpp** [comment]
@alenrajsp

**Comment by alenrajsp** [comment]
Please close (Related PR #3)

**Comment by firefly-cpp** [comment]
Please add also the following preprint: https://arxiv.org/abs/2212.03669

**Comment by alenrajsp** [comment]
Please close :)

**Comment by firefly-cpp** [comment]
Thanks, @alenrajsp!
